### ISSUE TITLE
[problem] roi_pooling.so: undefined symbol: _ZN10tensorflow

### ISSUE THREAD

**Issue by adioshun** [bostondiditeam/MV3D#17]
hi all. 

I successfully run the `./src/make.sh` and `./src/data.py` with multiple modifications :(

Now I am trying to execute the `train.py`. however, I got following error : "roi_pooling.so: undefined symbol: _ZN10tensorflow" 

The `roi_pooling.so` is not a symbolic link, I copied it according the previous report. 

Does anyone solve this problem? 

Thanks in advanced. 

--------------------------------------
my environment 

- Google Cloud GPU (Tesla K80)
- Ubuntu 16.04
- Cuda 8.0 
- python 3.5 
- tensorflow-gpu

**Comment by adioshun** [comment]
[solved] I googled the issue and download recommended so file from the Internet.

**Comment by layssi** [comment]
@adioshun . Where did you get the so file. I did the same but nothing worked.

**Comment by layssi** [comment]
Had to downgrade tensorflow down (from 1.4 to 1.1)
