### ISSUE TITLE
about using KITTI dataset

### ISSUE THREAD

**Issue by Super-Tree** [bostondiditeam/MV3D#18]
Hello all ～
I have successfully run the ./src/make.sh and ./src/data.py with some personal modifications， Now I am trying to execute the train.py. However, in  train.py line 103 "with BatchLoading(data_splitter.training_bags, data_splitter.training_tags, require_shuffle=True) as training" ,as we can see,when i use kitti dataset,the variable"data_splitter" won't be defined,so the line will report an error "NameError: name 'data_splitter' is not defined",because   "data_splitter  " is only initialized in line 82 for didi2 dataset.

all in all，how should I initialize the class "data_splitter  "when using kitti dataset.

Thank you

**Comment by adioshun** [comment]
I used this [code](https://github.com/zxf8665905/didi-udacity-compatition/blob/development/src/train.py)
