### ISSUE TITLE
replicate results

### ISSUE THREAD

**Issue by fferroni** [bostondiditeam/MV3D#21]
Did you try and replicate results from the original paper? Does your implementation match the paper?

**Comment by myavartanoo** [comment]
I have the same question?

Thanks

**Comment by lancejchen** [comment]
Not yet, as far as I am aware of. This repo is mainly for didi-udacity self driving car competition(Udacity provided a different dataset other than KITTI), so our goal is really to achieve better rank in the competition, not replicate results. 

There are some differences between original paper and our implementation, such as you can choose resnet as base net and we haven't used exactly the same fuse net as described in the original paper. 


So this repo is able to train a slightly different MV3D and run the test dataset from didi udacity competition.

**Comment by fferroni** [comment]
Ok thanks you.
Could you also comment on the 3D bounding box proposals? In the code, I only see you doing 2D proposals using the conventional RPN ops. Then you also have this:
```
def top_box_to_box3d(boxes):

    num=len(boxes)
    boxes3d = np.zeros((num,8,3),dtype=np.float32)
    for n in range(num):
        x1,y1,x2,y2 = boxes[n]

        points = [ (x1,y1), (x1,y2), (x2,y2), (x2,y1) ]
        for k in range(4):
            xx,yy = points[k]
            x,y  = top_to_lidar_coords(xx,yy)
            boxes3d[n,k,  :] = x,y, -2  ## <todo>
            boxes3d[n,4+k,:] = x,y,0.4

    return boxes3d
```
where it looks like you are just assuming the z-direction spans the entire z direction?
Am I missing something?
