### ISSUE TITLE
run train.py error

### ISSUE THREAD

**Issue by Master658** [bostondiditeam/MV3D#25]
i successfully run make.sh and data.py 
when i  run train.py, i meet this error
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'RoiPoolGrad' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'; T in [DT_FLOAT]

anyone can help me ?thanks l lot

**Comment by Master658** [comment]
@zhl95 @zxf8665905

**Comment by Master658** [comment]
After reduce the version of tensorflow, it works.

**Comment by FightStone** [comment]
@Master658 
Hi, can you tell which version of tensorflow are you using?

**Comment by Master658** [comment]
hi！
I remember it seems to be tensorflow_gpu-1.2_cp35



fang_sh@neusoft.com
 
From: FightStone
Date: 2018-04-12 23:02
To: bostondiditeam/MV3D
CC: Fangshuo; Mention
Subject: Re: [bostondiditeam/MV3D] run train.py error (#25)
@Master658
Hi, can you tell which version of tensorflow are you using?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
--> --> 
--> 


---------------------------------------------------------------------------------------------------
Confidentiality Notice: The information contained in this e-mail and any accompanying attachment(s)
is intended only for the use of the intended recipient and may be confidential and/or privileged of
Neusoft Corporation, its subsidiaries and/or its affiliates. If any reader of this communication is
not the intended recipient, unauthorized use, forwarding, printing,  storing, disclosure or copying
is strictly prohibited, and may be unlawful.If you have received this communication in error,please
immediately notify the sender by return e-mail, and delete the original message and all copies from
your system. Thank you.
---------------------------------------------------------------------------------------------------
