### ISSUE TITLE
data.py error

### ISSUE THREAD

**Issue by phamquandung** [bostondiditeam/MV3D#38]
here:  src/lidar_data_preprocess/Python_to_C_Interface/ver3/LidarTopPreprocess.so
data.py: calling main function ... 
date 2011_09_26 and driver 0001
Traceback (most recent call last):
  File "src/data.py", line 779, in <module>
    preproces(data_dir, frames_index)
  File "src/data.py", line 703, in preproces
    data_in_single_driver(cfg.RAW_DATA_SETS_DIR, key, driver, frames_index)
  File "src/data.py", line 597, in data_in_single_driver
    raise ValueError('read_objects error!!!!!')
ValueError: read_objects error!!!!!

I tried to run data.py and the program got this error. I tried to fix it but couldn't. Anyone here has the same problem please help me

**Comment by vllsm** [comment]
hi, I am accounting the same error,  did u solve it, could u please help me

**Comment by zhaotudou** [comment]
hi, When I run "python data.py", I get this problem: AssertionError. could you u help me
