### ISSUE TITLE
When I run "python data.py", I get this problem: AssertionError .

### ISSUE THREAD

**Issue by zhaotudou** [bostondiditeam/MV3D#44]
here:  src\lidar_data_preprocess/Python_to_C_Interface/ver3/LidarTopPreprocess.so
Traceback (most recent call last):
  File "src/data.py", line 27, in <module>
    assert (os.path.exists(so_path))
AssertionError

**Comment by miaozujia** [comment]
hello,i have the same question, how do you handle it?
